export const EDIT_CHANGE = "EDIT_CHANGE";
export const DELETE_PICTURE = "DELETE_PICTURE";
export const FETCH_ALBUMS_REQUEST = "FETCH_ALBUMS_REQUEST";
export const FETCH_ALBUMS_FAILURE = "FETCH_ALBUMS_FAILURE";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ALBUMS_SUCCESS";




